apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-37145528
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQB+rhtaTLL6hE/CokOPFaEC7TcdzGTqslBpZFW0nRhhmnAVL6ABtPxP46WyHgDM9kki1WxjpBSiPLQ4LNjpmLQvcdsCNas7FPRQsaebJ2s6hIadP2heK4ywbdxNiXokM54GYd7FAriCOmCLI2d3rDO6DQevQW0dt9SO7lNAtq97OICPalHt44RnNg2qQTrSWrRnjEQ32Dmo7COQWcTthmrLHzcpy6UVJkNXJKksahGt+MOet9P3e6FenPVA4RnvYleC/9PPOQ/9k6vaooUTT8Cx+zYw24wm1+cFp+vTqJnMISBHfjcMDyMmd2y3qlR3OC8TQVma/npS4AbcsRbOVn4uonRjwjNcl72Jt0DJWwfKqHEOP78Ne3ytiUswt/BcAfJbhwbZ
    AWS_SECRET_ACCESS_KEY.: AQAHl+OOWQl344xw0jrii87qSuJwL31Fb9VsViNzxlYDm2PdvvAxY+1pl+QA/eIjv4zMutNy7DOivvKT30Z7S3hoKx7siTuXmqQ/hNoohRQpVfXBys47UzLh0J3CV7MQKeRKWObbOXCTDLcC8j8Ze8fkCBEv5afVyMuVp+e1pNM1hUQ+qZOz/mpl+RPDiK71Scek1w/t/xS8pAvvCH4lKEgvJnFSbvIkjcrY+44sZdWU1bUShqnvRnGB3Sl3sqeIm+f+mHyULJS2B5yiywTgqadFPT6CANP5S6Ltn35PBn0pcNVBLy96cRsJE4f5L6KdVOhKXKmkr5mKd+HVfyxI7iJ3IMt65jyW4M3QPHpIF2hae2DCP24wSJ/lt4+hUkZ2D81gtiCU9DtPR/5HUAjtHFo+x0JiTpKs/NQ=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-37145528
      namespace: default

