apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  name: workflow-handler1-task1-767752
  project: rauto-eaas-767752
spec:
  config:
    function:
      cpuLimitMilli: "1024"
      language: go
      memoryLimitMb: "512"
      name: go
      skipBuild: false
      source: "package function\n\nimport (\n\t\"context\"\n\t\"fmt\"\n\n\tsdk \"github.com/RafaySystems/function-templates/sdk/go\"\n)\n\nfunc
        Handle(ctx context.Context, logger sdk.Logger, req sdk.Request) (sdk.Response,
        error) {\n\tlogger.Info(\"received request\", \"req\", req)\n\n\tcounter :=
        0.0\n\tif prev, ok := req[\"previous\"]; ok {\n\t\tlogger.Info(\"previous
        request\", \"prev\", prev)\n\t\tcounter = prev.(map[string]any)[\"counter\"].(float64)\n\t}\n\n\tresp
        := make(sdk.Response)\n\tresp[\"output\"] = \"Hello World\"\n\tresp[\"request\"]
        = req\n\n\tif err, ok := req[\"error\"]; ok {\n\t\terrString, _ := err.(string)\n\t\tswitch
        errString {\n\t\tcase \"execute_again\":\n\t\t\tif counter > 1 {\n\t\t\t\tbreak\n\t\t\t}\n\t\t\treturn
        nil, sdk.NewErrExecuteAgain(errString, map[string]any{\n\t\t\t\t\"rkey\":
        \   \"rvalue\",\n\t\t\t\t\"counter\": counter + 1,\n\t\t\t})\n\t\tcase \"transient\":\n\t\t\treturn
        nil, sdk.NewErrTransient(errString)\n\t\tcase \"failed\":\n\t\t\treturn nil,
        sdk.NewErrFailed(errString)\n\t\tdefault:\n\t\t\treturn nil, fmt.Errorf(\"unknown
        error: %s\", errString)\n\t\t}\n\t}\n\n\treturn sdk.Response(resp), nil\n}\n"
      targetPlatforms:
      - linux/amd64
    type: function
  inputs:
  - name: rauto-task1-767752
  outputs:
    rauto: $(current.output.hello)$
    test2: value2
