apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-config
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY.: AQBG2Z7PMfGTjk0gwMO/Tj0p1H7nbdQOfRzhv9FsOuk2RynqjmnGyiQ6lSHK0zTgKnWpQg6u1uizFfp3W8lf/qecSrT3XyJ+WVEP4+1xNB0mfoNj1JouJ6N4EBx2hq2QvyxF1Di5/kKyUzzjptzUexeLVnoFjm1tlvCVBsUMZXRd4tB851N90uRsSWmW365iZadPF2c/HLBGTYIAKIzCWuv21lnNd+Lfh2a6nX6zFyRO3xKIHOR+IhuiuYtFbhELKwU/VqkBvLiRHkclSphZHLDqaQuRhEHZzsdmiSivgjOzQRltTtGffi+UUy+hZnXK6Ge4apf99t+sy0eecwkCfS0sI8YTi8DdopI0gegI/6kZyQ/RfqZS/trF0ct1RS1+tkboKdwI
    AWS_SECRET_KEY.: AQB+QSuayiEv/cujilmljhTyQXvBssz93c0L0DgEiLnAtDn+JKDh2GM0C3qXLE5QkzTl9z7KAUZpfuJIXwP8gC2sTwOH+QcA6shBCOrd4GdHy4R6+iL61T9ViQgjaJObVl6Ad2o+JM7u5ZF2uy/JB/db4RshHStwssC5TrLJF+ZMgHZlHb/IudasxEeLnfnv4audQO+HpsE00gmTnPf+Oyr9ChElOCNa7PRy7Fh160qFSqiQSwdVtfI7VOZCvro6WKFEJ5oYQM02MAjZH//jQ1CdLR4JwfIDGcnMFcuexcBh39kv7AN/c27FQgztScb7liDmfYfziiECYEiDoJ18I8o9JraNv5tQ2cHbehsUilmzmwks0Z78YVzuJsrA9i2xwcK5xYaVN1aOhU0i5YycgvKc575s99+LoGQ=
  template:
    metadata:
      creationTimestamp: null
      name: akshay-config
      namespace: default

