apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-491148334
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQAIzQmjFvqDa21GXgV2IK9Ak3XH2WxSI9WS37kFzIB3Mu/ii+IAXXFoftXXM5l9d/oGRQZAItRSNS7ed38VYvLY+8uy4OtNs1agXLLzwo6MXCcSWdCzuAjW61dVXWvIBxMXQaDbKe5h5AfNRSr/wXyh/DSmiqX+zE4Apwtum2QJPABqRYLTmZAhBoI3fUUBmBQ8d/lcmuqxipdvGboXJcPMx4yOoaT86f0jWvBHyAPtRnirAfpbxx6tK53EMrfOTnz2s1fZ/t2UdvWl2i17k/oqbzUHYQKcQp/71EGuB3B78O6u20zKbKd14VGZUjaxH/jqhffCMYNzlz2KCCjnlSSHc7VVR5iniqZ/4AJvNgfkVtl4/NeI88ceRjeroYsYCKCiuXVN
    AWS_SECRET_ACCESS_KEY.: AQAuJd9Gnw3yoSQJKJl6PVCXsjcCAdB4i7rdpT5Mr4FNsBuBPkV9tDRiiPIzWn8KmqbPTYN12KhkBm0AEEqkSQR4LasJGkff2LbaK/wXqyjsFqmx3bNXTFl8ypSZJ/hvmEW7HIhYOHlmvPW3ZVuT6FBKLt8HYhGZDMayP2PkMekxnSGEM4rv4BSwTyqimbKe8D0B2VTo523ex+i7JFfqeVEsuL7lzNEedyV5Nv+ndLe4PTL0B7Beeqb3YUqK+PsGcq+8hNC+SK27iF/f+NRYLuBQJw9846XHi7IjRBjA6VvCmfXGzM3fcn8Tm+57Uo0MgF0QuFd3SMg7/l28ZoPZqXFjx4XDVVYrEEp56iAmUpuljvi15Uw/JxFbu/jsj8LQCA+5ea/aeGv4Cn1q2lwnBCRefR1PN1FGRIE=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-491148334
      namespace: default

