apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-103339752
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQA+NT/jO78ogtQBFVvCP1j6fsv581EgDhhXLNPv7YPSmPlxGccZdRW8hxVs+aHpkm/gMo5Ca3R+mwe4uIqT4cC+CecW/gE5SkXMTUzhblJ4l/DO5QD8VgZTwtAoEVVDtSKNyLxxCyAVUONqA2DGdHnNDvkmSw4ahbODoswyj5VWmwFiYT8+FtUU5CUgD/xvK5YSYOQArdW3jxm8KZCcnTZnxk0rjW3myZVS8MkYlGZ5TnYKAT0J7IETeeCu9KRBUcEnlN8XVWYP/mhnYFs3AJ1v9HZqoYerLcAaaGwkjTbvS67yF/iE6MwyV7tXV0vqa+PllCSY7DJDImENJxGGwP00T+/4SJ5MgGwItN+sHYFI/rZ1PkBaUTlJ3X3kpsYeHZlz0lgZ
    AWS_SECRET_ACCESS_KEY.: AQBKpSvNHa3EGNeOs6IWxS0GK8J59Pc26QorgmQP2wlZPZTpJSlaN7Q5Zu0jCAUoZ+4j1c3vPkOoTciKJR7MutvDMk03HKi30qWqUBEoCDa6MWBO1TjrHafRpyp8Xws3+MJ4/xCRhRJToELp2G8qaIrxoNWqVJX5QjMjGvLv4LXQWUioOLHXG2J68ys6/fKhwMY5WRibyhcS8gySILFfY/HoTQ3++7WC5hItrrNajAG0YWZoCS5VXeIkxOfS4s8+oyy2cWCi5uZ4zGBp2V9p19XKmHACv9zPj9iELAH/4+1ks+OMBAPZlRivhaA9QfDVxMEMqaONrEnbIngkWvqyeBcH+IV9lYsNrEjquZjbiCKc6qaXiPet+4j0tANA7wXba5qVgjw7u67TSPnnAG/SUAh519odslSfFUA=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-103339752
      namespace: default

