apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-192777835
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQCSJw4tWmSF77/ovuKEEsc56xDAqiFY0cgp1ksW2WkwWaMEvEBFbS+X0oqMLFX46UFF6naUlG1mVKOvAQVSWxrg6WwQyAH/xXHJE/WX44Gww+iu/eK/LKp8XAp1GaX/oa4A5qVY8Oa18i5DmyIYj2VM3uwilMcuodn0j1Fg/Hoi4U2PvPMW5vUcJMKDZMoIcHh+RBB/VjUJ3jYR5tXi29BBovD1gTa42na6mxyGh3E5CzyLoO7SEdQsBBdCnNPKEQlX4VXAIOpowbQWdOr+i9UD3VS7T259TMf9/IA6h1GHOE7qUgJEt5UGczbz3IZaoQPnZ5DRjXAsHk+L3SC5sE8gILXdMbwS3pJUUDFxKX1XOrK+AAjQrWeqx4pzJtxaeLy/IdL/
    AWS_SECRET_ACCESS_KEY.: AQA03bBpshvsSpKKJwIPM5YWOmVbDpgWgLpHNyI+Au3hHiWwrjaWotC8XQKd93h0rvr+5PVCTeKX5nXJzu/mWP1NpLtbwWDIVArIsIiLMuAR13yuMAXGAv59J09+yVTZYRzvcvE8iwglQ6IfLeewmzabYAYmBIDL9SfDQR9IU10a5HBN2N4ErkKJvr2WhDw8Unbf/+aDi7B9O/oeYpnVWcTObgPRbM0pO08G0aBxGizMKLJRe7fkj+6aGppO/5bUXo+dvkRUUNkwj2R6kI4nt98frl+Gm/z5P1za2ZTGBYPET9HeuiN9wcfsdSkpX74sjNlaIFXFneKGx2+iP3La3wqT3FNj+Ky0guEnoXX6v4OHHcWu6Vx++s8wRmUaLauIMyCRO4dxpPYaVRdWUhg0fTUwB4SqakeDcjw=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-192777835
      namespace: default

