apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-928686566
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQCHE7g8Jt+usQ9db8JzYy15nbeTgzRDk0gHX2T9nLQI8P+NORH/JhcYHRh49+GIfGgQI/pA772yOVOUR5/JO9G8e6hHtNUSzl6TvHGraBE9ZoZgT+47erTZrNVFKXWjLNTwV5PRF9806xGYXaAntofPvUlThn7cyKq+z0cxdhv/maC9qEbsJvzDzvrrYI5u8X0XBI1HhiHU7weOo6ReDjGLPZjKwPCJ2UDynOlhe2P4XVUgipVd44KDm1eQE0zfI6U1VhvAYwQY/Gie8cmQaMrivuvOEP+vTVsx5q1Ykq+3BV5mE+ggd0r/ejQQYjIPIbm9l5WsASR544xR6Y5b0jIEEio65cTKitBkB2msKUKpVJoOQGAxQyangN0Q7FRZss3ddZIG
    AWS_SECRET_ACCESS_KEY.: AQAB9HH+TW7QNssc+ray9cWiR+vRqWCOTvSmOQTlUvTjVBCa7iSjRK4r8l5z1mpq6Bo0xPE6xihs136eub/oTfhoZM84VcqAKY1a6ad4l9dO5RGv8bcoY+FKVOiqqLso4S/frbFUj4w73WZ4L3oC0o3gP6AmrQb+ekeTDfSkGnKE10LaTqyHxz6bl/CpaA/SGyt1nQaaqnvUh7XhWVyobQcu1g8NjqsUKHUtyPKf8jYtKoq+vu+A2yF3dh4IV/sXOPN+ByJiz+TWFgFR/B623sya6bINhAgO2zRmgKoUx1DTr2wFVCndMGaQMTFKGQGo1V6JLQZsQ2DwW/fgvA65CENLVuGTXpqQHYgtSvEIouAR53rRM8tN3I1wgDRckcEw5lbXoGWWy1CHNFzp0MwvDyevPLu3vchDBnw=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-928686566
      namespace: default

