apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-43974449
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQBQ8pBkXc27QOBRo0IvMQIhyBrFtxwAxQAVW7lCMXamBPJEt+mxrScvNcUNqIMPV6u4UVYYRyTrAKZ6QFodVyHW5wKw4eZDOW2XlnkufSBGT4QC71EG+fBTfuH6yLoYCXng8ooLUBdldiAlu0MCZHQSZ36zNroojyz23jgzV6x9FVb7ow/q3lBG47RGEwc+6ke4NqYfKTQZ/z8D85rbmqieheZKuDs9R4P2yBX5/Fdwew8h9Hf4AR6s0zdAfR2/9XjUUYEmuZsy9TK84Kb5qs1dcObSoryf3Zb5h71KBg5MlWc+OtZ4Yq0n/lfPJLORE7qxreO/HUFAXPQndaxfUDpraQ3817tQjkjOzoCKy67YY5NCwfCahap4agwjFaUBlPu6nbhH
    AWS_SECRET_ACCESS_KEY.: AQAWbI15vs8mNVzKnORxlfja7Pv6ngttj6OEQVe54ROMyIBerELjtFADyBEU8A+Op+BWf8Adye9C0CHyZzEe5JzRPlC3I1gvHEzE07yPNoe6lVDTFOitowSPgKgPBJIz28SbNkULF0OpEESd+k69XzOvr1rCquS2J8mjdVc7JIwfjVHEZWQLOdNUu4Jfn1/f1b16u3cGrEV0xQpIKQxE8a8JK6Q2FdqyCge2CSPw9V8yTCGUsnpevWOVzoxJQ6aggaVdsTU2I4CvbIAh0iZFEtGB54JbKGhOeVCiLRerozTBqvQRCXn+8ayt+Vlsnt7hIbbTgs2DrJHHGWIa1vAplSsE8d3SdcW4KNqK78C/B9VGna+qKNY3nDKa0d0K97d2W8pCmEAfGecT7VeUQLfGqOM0NMNLvmeyEAA=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-43974449
      namespace: default

