apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: auto-resourcetemplate-928686566
  project: akshay-2
spec:
  agents:
  - name: test-agent
  contexts:
  - name: auto-configcontext-928686566
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
  repositoryOptions:
    branch: main
    directoryPath: workloads/eaas/terraform-guides/infrastructure-as-code/aws-ec2-instance/
    name: example-2
  version: v1
  versionState: draft
