apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: auto-resourcetemplate-168786706
  project: akshay-2
spec:
  agents:
  - name: test-agent
  contexts:
  - name: auto-configcontext-168786706
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
  repositoryOptions:
    branch: main
    directoryPath: .
    name: example-2
  variables:
  - name: ami_id
    value: ami-0854e54abaeae283b
    valueType: text
  - name: instance_name
    value: auto-ubuntu2-168786706
    valueType: text
  - name: instance_type
    value: t3.micro
    valueType: text
  version: v1
  versionState: draft
