apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rt2
  project: akshay-2
spec:
  provider: custom
  providerOptions:
    custom:
      tasks:
      - name: w1
        onFailure: unspecified
        skipConfig: {}
        type: workflowHandler
        workflowHandler:
          name: vr-wfh2
  version: v1
  versionState: draft
