apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-434942608
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQAJxzmeANbJPhfwKVN6dDIt2SEkMjJVuOc4QxBCmVaNwiPYzCAnOuBDUpZd72Rk9e6ycFpP9LWmIC5FW+H+SBp0NJ3Mltf1YFJJUf2RZuK50j9ttgi8GKonOFrmgAZjOVgW1DWFLDwdh4Fwd4BUpDtd++G3bAL4o/CopIHfDrzJ8rDNkQzTL7RaFEy7ywALXqbWh1Amk8oEImfWjyJLD1npSLGp/ukRj9ctPatT5tq5ZzGipU8rOq+hMjl8obu4mhhYc+P1su+WFNuxnOAACPQBh48i3P2Ws7yWLx7AyKeHa76sR1AUumQdsV9fZlSI/6+TaIQrZRrdq0aMKKhvOWN04CTVfN1BvE68++sSeEXCYt6tClofZmpvk60rOFNtP4+7kkdc
    AWS_SECRET_ACCESS_KEY.: AQA9B8pmipIprG7GUYjXevLxrbkCLsOcu3RuboEBhxbosQROoqmlDthJiE0fQlMpMsUCOUXF770zVNBpUNI4u6J8vgQJpDJ/tx1/YPIXUxqB071UTRhUM7Qxb1NQVkaFoCLhT9bu6DvSrUKLBkLhkpKAEnQ6s/fFJrap0q7JRAXWGT7zWrz1EkECR44pk5eGuk0ZUxH1tFyWPKTKeskPTeWqVtzN683eaKKcy+wKQtvjIzanhkBVeA5uVnyaIllABCIWiC8+107Bqcr5wAYH2pIxZT/gfgEVwRMbtu+eLC0GGyGGgDF2Z7RZHwslasfBP5NGRTHKiKijHnoK9qw6b4Cvjjgs4FIQT5kveNpBFwLNOOQ0xTtsmHjOPCAxEdZ9eNd3Ny/xOA0uLb7Q5HApG+f8BFVlz6KCDTU=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-434942608
      namespace: default

