apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-197378438
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQB/Kzc3y2yQOPhWFWlnJLfn9ylhlcm/MLON2FzsOdPlG8f6RUxO4Jto1GaccUoEIcnPLbBWPfJg3foeCkVH+Ul6lbUi8jRPEwJGHXRl4CIEesilL63qHbmUzFHAuJuDFboeg4ja3FlbJQQxDc6bDVyyXOY+YBtgAoAsArUOUZCmzTAoF2hHLD8mSQmOFh0SP54BO3TtN32amPixVflZIXRLxX6bBHNAcStX0KYXREPfIlwxayPKhUvshz2wXG25tnVRLl0tY/Rv4aPlQSg3cOgBovIdBMSmWReCKUWhKyye3sabnGcOLBNjBQQDkX3ws1n/HI57n3XiVK9aIFgJws+Xumus9JrzhBA4vzovPxeyfmUUElZ50XvEGRm8XKzkfeNy13w1
    AWS_SECRET_ACCESS_KEY.: AQBokfqguQsJhiGf2jdQQbQjm8N+3kOdvbHwiUK9APGZuFIBjO95RxAUPVaTmWHoDePMrWIRCSDRqPaqdPz9gHy3p0mmSGUpcn0zojEI6dTZ51x1DtXJ63VaCcmxkKKzMffPWBRo0Fpr44YYi7ghQGdXlFz4TCXKrMPn3QFdDfAd0zUeIa1Oehyb3Qu6khFcGjX9S4vfHhOaqphcIb5HL+FsRNBDb5wOBSfgSKWzpbl+5MQf5M+S7zh3/lx/l93UoN+wTBSn+07kPvNIGVAetXJ8RN6GoTrqvG+QYG4/j1Rd5BuvebzStKQEUzZklHp8OTHwmVlSGYBIV98gE6wem4jwTwGEiJ2W7uI0a1cajvVPQ8S4QsPmAr6xbd+Th/+gCoBK1YhdItIlLwYnQOoRKoee3OkzV7mdtpk=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-197378438
      namespace: default

