apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAiEgqKNG/+v8CB1YtowoknR/UUZlAxuuYgGeUqQ4gGUoVZfbzOn4LG5pNZ2GT24jCxWVsV4XO7KHHgjMzHPttWEFHxDtNtEJY7/KLVf9lz5ZhohKvbtxtD3KLyNP0YS1KBeGZyRVT2/WM6YbqgdvLpoSivbPliMR1jC4kmgJiETCis7Cf4ZsE4yuOgov03Uj0HVVZ761beav286oLkfaJdKWU81/LXlN7VmySszgHdHKlNFx8lirM9ue5A6q+VnS4Ic2UtRDlshVzgc4QGfxglnaKqXFfgvKCcsA4ltc27oaJma3PkHjBkSKRhRZXaZXuS7HottRKhWq8FiG67HewAv8FMAxiHrsvMabXnRKdi51OU0sG1KCOzuAqFZF9xWBpBiiiDG+yNiV3qf3Gt7AMoaAYz5r7eCkI=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-git-repo
      namespace: default

