apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBu3Ael8tbYQjDqeBksTtRVbi/rn7iHBMTlzIcSSvTrFlolLUmb9kqaaT2eCRUYcB2mmdSeYj0js8Oh0yj2VYxVw2A2Ok0Y39U00wHZNJZ5+Rm4KHkYafTUdEqy9S/7iZ5+otDCPL/UU7Pw5zPfZCcSBnhIn8mjmIXa+3XJpJZF3X1x/zEqUngRKrV0L72aZWvZe3dL9l4a1jnsxK8KVwoentikxMG1bcu+Rdd4/5pvblbvJZZ7Q6moSupST4/UHM4MsKg6167LtvCqQojCuDT2Zz3nVPhzfUtQ1ElRnNNHFV6FWxzjgFjUtrqn6VnbuBULIaaJY2JNogNMipRqwBs75BTMwWWKL6IC+4ojf4OvMd5gzeoyPWUvLPGJmL1GfiFQZgysNz50V/V3L25ueKDo74glIMvTwYA=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-git-repo
      namespace: default

