apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-552116980
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQBfVPqAWy0UUUfp36Xi0pvOMvE0UHxUzWX7e7xiE3ZD42huh7MBFiZO7WD0QwVqfFn9jKTLXdOdyG33ixyFVEHwesz/sQEAgNr8iF2itObqXE2BdDmApXG5afTSrL2fjHTbC0ucSOhBZ1Fu8L/C+nBohu28PYBuV0PYevcLGyBFR8i+19NPO9lfY+qqwdV4lL2fN+yFw9Mj7WCh5x1SCkUUz5OXWq2PJLfuGRUN54ButPSbwm/J4kZyrv1GetHzArXfcBR+iuD60Wq1QJcGa476YzmmPzGYO1MYiSuiDgkHKwb7I2iLijj8JkwbZtvaKxdDUl/FCb0FUM1Otp5cEvgRKhKUQh3vYkOORa19KCV9CvjG1TbBjcyXIsZnjPkUIsUg+l+g
    AWS_SECRET_ACCESS_KEY.: AQBwfC/rv12CH8O/NLWePov78qe2A2EFZ5gItppRfZDEUQewHlJmPx2+ym0NVJmy18GSGMnk0SfPruTY18ReWGrZm/Hw2gW4rfN8Gy5nrubbalVLtbnKo8HGpy9quf2RelVdrj+38p+cEQIG8LxQC9XqYXS2fYdo/GulxXggpWn21cvPzHRH/J4TDdbERLv2nTLbsedJflDq4w/SPcIC/ah9Q/AOUaB9HBNPY+33OmbUsyxqO1zxFSBTvD6l/Vy6L7wGV4OEV96AZlpIFXLyizGmJxtfLEVRqpOH9VE4JygTM/xtvDV55nc5i4gh6qBgaRHetwAiFc9V0WQUtJeyV1e7Fmbtm0a05gV0x+Mt57MxASKpOeElSOZcsCyfy2bLXmJIo8XTO41Ap6bXbJWgRRgzFp9t7G6GDiw=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-552116980
      namespace: default

