apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: env5
  project: akshay-2
spec:
  agents:
  - name: test-agent
  template:
    name: et3
    version: "1"
    versionState: unspecified
