apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBCg1K8L40JvNw4nTZGM5nPvMC8JwCcYmJEikCs8ddOk2tzdpEc8Sh6dhLv3jnuc0fAw9Sb5RKnW0FCDDy5n9KbSjB/sWvQQRwh35DqcoiwykqPZxCg253ULr3c3rYb7BYsmbIcyfnEh5KtjfsXUC2oRFv8ntP9XH570nWBFWKYOSkJYjqOTNEVVCUT7IzF4Vn0889pUDrvrJb7DQOsLnTv6KvRkO68cUGLLBqlsqVZI2Z1EfzJdlE91Y0dLC5ktRHuH6VTIFlJ74I1HzsDFFr6Jc2Q3I9yi3+wmdo6tjC9HpJpTxYRr8QhyIsWCYh6lYVINJ/qt5WBEvF6FFnfF4nubRdEKZHbFZgXvpOXOY1RvkdIg8Jm0CajSS0fGQMrmsDzMNEmYq+T6ytl1BW/q3HBoZ2Ld/PF1zCtta2jNjvadMX18IV0ZZ34rL5J8m5WKtNZ7AcvyaRbQNNM1v+8VZZF9WMdnyln9pl7/oDtVw==
  template:
    metadata:
      creationTimestamp: null
      name: akshay-repo
      namespace: default

