apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  description: for practice
  name: akshay-terraform-test1
  project: akshay-2
spec:
  agents:
  - name: test-agent
  endpoint: https://github.com/akshayenuguru/teraform-test1.git
  options: {}
  type: Git
