apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-aws-config-config-context-541257
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQBH/UfxwS+UYunuvwek3B6+ldqWzOH5ZGBSUIkhmB15Yd31LdXSiZgTBzSoTtZzYGkjzo4DG/4lp15W8WxLCHhLlxBeAgvctLHrsI81plkaEmH+ylb4/dwJ96eF23DU5cOInab+BXjmBGf/qEWxPTavg2W9eVU21B9yRr3yvOaZb38OKAf7CJcRXW1/XLwjF3xHxbEl4Kd2yAqVXR054xYMLj+klBeopSvfqXEKmq6QD/6LlJOenit+/4szaKRGYB4DejwGOfVSflLSNjJ6lpml9tGNd+zjg65hJ9bQKBOPaHpJ5iig4SBWYz/sGLd9ClrdFYwu6nXDwt6j6Yj/uUzdoWeuS5pAwWLj8aBrzkUzJAme9VeRmbcVCpg+iQNVFktXSUEG
    AWS_SECRET_ACCESS_KEY.: AQA19s02/U98LqiJ6YQQfvBAF1UOiYh4FmE8SbJpLab5i2MXSKWdP5UGD0lr0gQ3zMJGr/zNZ6sVLVjUhBZwtHfoUyTFCgYY2XY5Wq3iG8/AS+MYbtiiY7N02+Pr0LqiJlKzWX5eLN75WIinmuhl4AmORS7NHhHqRG6wrYIy3zQlaoRmnX9D2J2w/GqXa6OI087HSA0nTJh1JqmZlcG1COWxkZQjZkIS/AkJYdvTBZGaUMDQYfak7UaGq3s/ENrcY07baWZqFH00Y6ICeS9FS2kFee2aSPEyReIAFveG4K4tChkBVj5pfQKa41DxW/8dtO7pB2ery3uZOjKHL5vR3ckF9MY4V46RLoz04etjqtSzpJn2qu3r/nwka5Q5IuHVHeo4/tojLZH2N+QIipYiTej03nDXEO2GRU4=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-aws-config-config-context-541257
      namespace: default

