apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-42321516
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQAQypdAImjh5yFwUCp0nXQNbdVANYU8BdE9lcRQD3Qbk62UOWpg/ayNHny16SNCv5ndlqZ2rwO+8YGfAlwk+6dMqCTJHFIJCtmkhM1TLOXYqjQuF5kX4mDCCkXCA65Dso/ZuZ6tB3Oj5DyWe1Xg5Sg2BDgfMAl3x38S9PvVy5R1IIU5LuM1NgRuJMqAkiJTDHqW1GSXUgCjyZcOQyKFRiMgVg6NEM2DRgEaAGEkvLuuoU2YML4oIR0rAyvZftOzKxKD6iHfMry8l5VGB50gUmj/30jwmG9xAeiMsjpCaBlW73Y997lmx7Om3fn2WrSGYS6S5jizNUOSG1/mWrnk0UB/DJYLBo5aI2UQf05r/b2giBIohnuaDZsHTUsE3PTy5Yfl7QCf
    AWS_SECRET_ACCESS_KEY.: AQBhu6dCYlMXIcuFtDTYZbNfb0l4jtOKAJFDpi7gwaxL5rW2P7FMrAnBeGXqCSdJvPdZpdaWDrQaAThqiysXt18UmPGLi5QOodCwjA5KlDqUKFXsh+fEfXHfs7CGutJmZc4mVrV6pacLe3ZoalJJq6R5aRNO+KW6O4d+SAFjlr3YKAZaphqHAHpU9HrH18XxI9pLp0FTpuar4h0MC5rXvr87oRvaFVDMRP1f371/BDyBapEtug9H+sWxITtsaOAEk7wwLd/GDjaaqTCYfqm6XaVhbctrCUAHlFJ9jV718eAq8Wa7nT7YHvP6X8Ltjr5vqSW+3Ja9cLbZdLPuohnxJK0e/zEMiUcsndShTd8erXJNI/MHOolEL6Y5UOTwHy/Rs3FNmi/taBSf0GwsHjRgMMLCFYjCWpce7oA=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-42321516
      namespace: default

