apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: rauto-infra-config-config-context-541257
  project: akshay-2
spec:
  envs:
  - key: INFRACOST_API_KEY
    options:
      mask: true
    sensitive: true
    value: sealed://INFRACOST_API_KEY.
  secret:
    name: file://artifacts/rauto-infra-config-config-context-541257/sealed-secret.yaml
