apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: rauto-aws-config-config-context-541257
  project: akshay-2
spec:
  envs:
  - key: AWS_ACCESS_KEY_ID
    options:
      mask: true
    sensitive: true
    value: sealed://AWS_ACCESS_KEY_ID.
  - key: AWS_SECRET_ACCESS_KEY
    options:
      mask: true
    sensitive: true
    value: sealed://AWS_SECRET_ACCESS_KEY.
  secret:
    name: file://artifacts/rauto-aws-config-config-context-541257/sealed-secret.yaml
