apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-559033448
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQAAK3IJHLuVBWKD//9LGp8RAkqBBXd58/kU6+qbMZKqdbE3LKs78lNfWo95a5TT04KZ+xuFspCsOridtXicQR5beRAqdHCoAGWCd4scun9Hqf8E8VUXVF1OSKmRVjHZ61kqqPoCzLMn8ycuUZgwhHqdYfNFCmU7YYTHy/EazMiqflXP7JLTrGmYe09ZE0h6fbDEdJlciAYoDnW5vcRboV5Y4FImd2BU87VOjy0AxJEuQ5EVrqexAcfszHeuuFOT7DxtkVkapzpJS1nXKqQ7I1CDWbx9Oefn8wwnhIJJGBZ1mFiFmPQ7Mb6QVhO+JsFV5DtSRXW2YY8KNU/1xYY4zD4MF/Hu7d2AnrVLWF/rsZ1VRxcQTIhygLvuMLzxwD6UlBowtx/P
    AWS_SECRET_ACCESS_KEY.: AQACDs5CbtPpQsMDViMFU1NlBFKRcfp/Cc6XFBhOVxsSjb5+Fg4dz0q04G1dLrAhshQawlmmDE+7SGW29B3y5tN5PyJ68F/2G3PKQtPqhBmb1pX2XwzUiZh9kIR1vGEaladJkaAkazrHUNSHsRyrDZRZ+9ti0zuyLrgQ2vdWb/wsGZlV9O+UYTlYgtlYbIzMl/N5dmN8dxaARMVEuoBMmzyjnlI6ygNwDpdXxVpGTYNoHb1aBvHS7bq0bbH2g8K3WZuL6W+QWSfhU8yvN/8v82csfxROjoJwXEKDDLIdOq1jBuoiHDt39OPnmJEFQcycAvOFAKzJjhLqQCVEe129e5MS4utEK+hf5VELvPEGT9uV6gHrlXhyvJdyLVKDZKnk0s5ICwfJTh7ct5S4qiOU5iSvcLsGU0WPujg=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-559033448
      namespace: default

