apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-terraform-test1
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY.: AQBVKVjJwl7t3aaFfo1gW5KuhgRaRvLQ18J4yCpo1IfemCLRfEeNruEUQxICR3/207M0TGBOaYZ4APvdOpmUcBdYVNfQlALkE7stmnTkQeBKuvfFJ5tXcfYOHRCI9TXr4CC71L0qYQP8BNlJexrBwPabisd2tCGBaMQfP3GSmPw+HAkxg1V0FJxQ6nnVHLdbi1TmdHYfTkDv0dz4KHJLBI9FEoH+8UyRfRIWgi9Z67NCYfaB1/lsVEf29rUPDzR7CSrePTAvPma5XAShqsfm1kwfRziWVG0qwMwkWCwq9GX0xpMq1Blgupyy5flmKk55z3Dmc4Kljjatyuy63sIwd0h7Yg8IihwSFBOGRpnT+JJEkDXbwBjZvfkkRqePLWdhqQCDcmuh
    AWS_SECRET_KEY.: AQB/0fZbdOnUFIVP6z25TaUU8kAL3ZqlLbHE0z3ukzlOiFmTO6Ya4l315KDcw850DhKDcRKdD3siBih7EBxwiluuOiHeglle3eBppVvUXLBi7ZCYRZmDjK3M1Yt5rlH2R9YcIGFU+2Yu9692+vHE0E4qp4cvIyc4glnCW6E3ieNN9ItkGiJNrWZkG0d23AG7TstMrEvqMlZqa+qrCG7c82hBza+jb3LH4ztPPAGaOa1pPsOsxl8LM3cITR4pA+9TAuCga0chFxATENCDJ7ysedXuwzJfzh9lt7zm0s4N0JeqOs0L+tFej6/9GC/SMLoC+4vtplz1P5jLLs0Vx1cSt2XjshqPKpqTB7PYCGHCW75Rw1GLaJnqaBjLhQNDASpvA99NmAtp06AJ9oM+n43qgo8OZucQYr1e+F8=
  template:
    metadata:
      creationTimestamp: null
      name: akshay-terraform-test1
      namespace: default

