apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-helm-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAG1HRXniAn6EgT0MHGkn7PopA481MbWdS6al7GFTxljoSqMvxCtPrhR+4B7saxb8Au6m94Z7/874TKjQMrqaDoGoM3FNMKoENJgCZsXHLQc/To7baQ2eqpOF2MkOcfHNef59FOyowjGidW/bWzkqy/yBThmKXejKsNsOrH6Qq5NA09lSPEoWOtap32Loya2GwL2QKrkLOCkguHxjdKe+VLXL4tQzrU80E6vSRFa6yQ81svgdD6LN5t6ZQvEYRUFilx8CvV9qruZIbcDYCG8A4r6M20EKOjpYPm5wuvbbamLWX/l3p6GHAdA+pzsQw16qootYr4ik+Ugs2U8x7wERuz+mUh2VPUZvR6+qYCJmTEujppfIBvhhDNDzg=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-helm-repo
      namespace: default

