apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  labels:
    ns: "2"
  name: ns2
  project: akshay
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: akshay-pre-mks1
  resourceQuotas: {}
