apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  name: wfh3
  project: defaultproject
spec:
  config:
    function:
      image: registry.dev.rafay-edge.net/dev/python-func:20260410152429
      kubeOptions:
        securityContext:
          privileged: true
          readOnlyRootFileSystem: true
      language: python
      skipBuild: true
      targetPlatforms:
      - linux/amd64
    type: function
