apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCSsb6yztye01SocSAmKx49iKEtDtdXlpP2NW5/rveqHrEmWShtu0crlVn2zse7VmRkVMd7W63iw6tOXrLrTojiG6aEwqSa3aqLpUwInlSxuSRhARnpV8HcAxekFVJB5V90AsCVWqSYsQ5A/512ui5KjAJJPznS/BfNw0M/RFT1e42f/ATZgFT8Z6xsnEvbBPK/aaDgtQJKRU52zXTSGbkhfXmT+mZM+T3wV4rNWztqKu+QFVFWZ4Jk8rQV8UzeY6+RV5IRqIfHFJ6ymWIBVZ2RUcY6yxW76ZNd4QZmO6GiGmn6AEDm28xVYHwYtQzf8u01er4Cb4+te1Sp3Re5qoVBW8wGB+93ZRs1WJdwXtaYOnPBljCMvrz2XHcLWdsg/+nkaePCXFxdHem2/m8Uao3gmDPOUgBViQVWqrDASvRqnNXQvP2g/jNMdqOIctXeybv3t/P23knSLC+uCaUfomjazLTt5QyZOke6Cxo/Gw==
  template:
    metadata:
      creationTimestamp: null
      name: repo
      namespace: default

