apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-466090553
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQAD0Dumphi7UYnwPvoUkbjkqpBdVi4SBHbA3pRgxEj1zW6iwoyb4LHYYI1RVZGBwzFOtdOZYVMt1bhILs80D44hkH6MP0ZbyrDhPopv9Sn+iUcCAW/L0iklPWc0fLT5+zTl/BcSruBxcaXPrJwaO5O/ydJZ0g1fTjzg7obPfl1QMtMQ9qCoZi6m9XvyXa7hh/M1mC8DQQ7PVCNgLiOaElNFGMHAYxC1vJeX7dSUg2MHsEbytFNzoFNwIWlyP2yjWV0/QULEpu9BJDyF8mmxmNtpykVMWbAPxdLkNJ2H1pNucL71Sq5BzSEZ91Z3NDe4fNVvMYdG59YpRbhF9aPMlnI1422QY6bTPxRqDVMrvDBtBBm1RwyevCdlLkZUH6RG+GyYqMcP
    AWS_SECRET_ACCESS_KEY.: AQCLVIjiSg/n/TF12MR4ahE8uLUTGn/thqaeQeO0Pa0mO9FCaRIDhF2LlIe9Ti+AfsmiZbSZHoKSjy2iwx36YzY+4FnwezoB0Kw8AE7++rG8RXWruZxysZpzVxlD/2OUu5LWdx4p8EhvMkXNLZUtbsaNcySF6Dkb+ttFqltMYc7qQQS0CHRQB68j2TKSiIQfoW8M0t1WVIP/31Cpge0M8lOVWSNR/DpOs//lBpqJFIOfxUjpNht/aK8QluiEZDKsvp7Bhq6Xq7tgBJts9WXcjIXaKAyWa5/K0jx9GP+gaDR0ExaH2sv7DE4ZUSMau1BdgjZwpH+iwODL/+HZzaBycMMFZ8QZ7IKtrObgSkgFGDW5b4V+3mQQgJ0IOdk94j3Zfm31Sq2ihBTAOaILGCmVIe/DX1p1bgn/5TQ=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-466090553
      namespace: default

