apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-876361132
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQAzXJ9knRNVo66Omzee3lAB2lxf2Hg8sD2Qcq3KiMATMy+EHdGejnbFvkVZKd79MdhNR05HK57HYL5QSMPdo+aVlxiR2KlsF1jZ8VIaGd7ffBa/doSsck/WCHBaMxbCqv/JkgrBtOOpH0mXz8vVvJhQdilG22vxAhLqvgn36x3nq2FeG3YM/fTM8Kq/DUGsyPdXSrNoD6yxMB/o7IAL6yqHrXT7r38aQe72vjH10J7+BRrC2pQYQTqaZDeRsxwGJC706bcSJIKQ/zcqlRyFu+oRxCL9LtR9wuyir3wqZ3AeYLm7e3oaHiPt232YQbppb1BMdzXQ/IuerespFBoSO4fvaDh2a5VPuG6ZY7qJ9HaGj3LunMo7dmh7+c76wehvVhGjR714
    AWS_SECRET_ACCESS_KEY.: AQCMgkUI9vZUWOZbB104Ui+8foLNOSB+9Wa5A/1q5JdB7Uaj7Ti2dAVRSmSaWs5etVuIAKgarmgqU3GdLTH/PnidbwYbBji6/7jny44hx+YCQyQNc7yXRwjndnTmFsdFSLiMGYt+yZJZHFUlcH+VVTBQUwezaAJnPSg2vrs17Ec6hyEBgnJ3+KGuOO4dQVoJ46TIWxaVp7mzhw4moXR+O4mzobIwJlO/nCI93Io2f71DORjNt0EUmBauQWmCfIdiNafkXqz9A/qOjxUHVTnAsaQmTksYB5u/qb9RkEAEaHwvh4SrxbguVot5YhOnJgM4bJ+3Ze2dF7c+m63sCnRhqzcu5KFIiyCem6GcdUrLdHA5QFPQ9r0LmiGvN13l2vvKLB/hE74NayKwI4Tm+smVz4D/6aoNiNzRkvg=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-876361132
      namespace: default

