apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: k8s-agent
  project: akshay
spec:
  active: true
  cluster:
    name: akshay-amd-pre
  config:
    concurrency: 51
    environment:
      numWorkers: 11
    kubernetes:
      limits:
        cpu: 251m
        memory: 1Gi
  type: Cluster
  version: r4.0.0
