apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-845854499
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQCaB9UXoY9H4L+1ncu4usl3QiLSrUCZAnOdkx2r4mBIEGic2j6KJlPzAZtp7eeh18cdO/jJ71tsHH3HYFPpr8x27/7MZfFLI2txeZE4Ku6AYif5v/owBmFEraEoZNeTHAJ8jJhhXQiqGrYAb3rzCv/IQj4n/d6LKvY3gSPsClJsMHPgdH5N8/yQgse6oO2H7FNNB3PcVvHz3UWY2vC/zf1lc9o3zra/QK81QJrF2WiH/9FyRUxLpctenrarEH+a6g/2GN9++btoKrm2PsJ+lmzi4LhbNAnzJQfn6bHMkApkiueuXBT1uPygYRgwWH6dMkn3E6M/LqAtc7vfO7ZAUBgfKODVI1bPG/w7gtsdkILUKePgxFhW0L4ItxlP10Ozg4gnDbrX
    AWS_SECRET_ACCESS_KEY.: AQB6GcpzXQ9K9M/iH8vGr0bbnDd007oK1X/qkqMuP7vOrzYRgM7oELjWD8mArJyTES1toOnt9QswPWInzw8oegZW9FjTQYd0Bsx4y1lY2oPChOXuSsVn3F28CkRiGzd4L99n6NtmjHMlUKkO/8KzFqUSYlA5glAVIwBJec3An2T7vAovE2Wy473DUSi3oP8CBkmwoBGIk3FIK8DAXzSLBrNuu1vzkLtYK2Bb7P6DBgIgyalRAJvZtkqvh22T/5IXXSzXBRHNUmWfubenNNKbSwlGZWFc1ZyfWr2MDD+TMiyQz/s7Zo1v6NM9X2lVkwU5lBfKU9ecpNuZRKrmSoIjCzD2Nj4Z2GfAC3OtWkG/81ZGmOLT1e7XlH2fUL02MQ5r4Fw2UfK8+/Stz8VmQiOSzfUH/YNwMvoKf60=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-845854499
      namespace: default

