apiVersion: eaas.envmgmt.io/v1
kind: EnvironmentTemplate
metadata:
  displayName: email-et-1
  name: email-et-1
  project: akshay-2
spec:
  agents:
  - name: test-agent
  allowScheduleOverrides: false
  resources:
  - kind: resourcetemplate
    name: email-rt1
    resourceOptions:
      version: v1
    type: dynamic
  version: v1
  versionState: draft
