apiVersion: eaas.envmgmt.io/v1
kind: EnvironmentTemplate
metadata:
  name: vr-et1
  project: akshay-2
spec:
  agents:
  - name: agent-doc-1
  allowScheduleOverrides: false
  resources:
  - kind: resourcetemplate
    name: vr-rt1
    resourceOptions:
      version: v1
    type: dynamic
  version: v1
  versionState: draft
