apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-168786706
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQB0Tv+DbS7PuKnWAdNoBy82jV4oNKNcJLrtANIOczuBG/CO6WwB2X19YxCdZzSUXEQtqLqaNr4gRze016/uMbL8yWGXWgyXg5zJK9nPaGJUoziWQE2uzolNbWGL/DIJNWv1jR4ue/4qYkxxJ4hHrYPmxsKBgJ9HBG+ic0h8YUGaKWWWTbngqmxqlSnv8LAV278vYun24Bkdd5oRVggWrpnzco1WXPJIQUCTLyuxLGEXlX4L+wdWgJpyaUAgpRd2AXTV9yZr/0LEC0lCpmw603//DaNihgQB+HowtwfOEOiV389xBqvaHVByDDFu+uFOuqOUI7vMB0BHmEHpdxw0oQHemABRnnpUklNe3IB4OK/E38wlcmViFf7KtFv1aL0LZY83YUjo
    AWS_SECRET_ACCESS_KEY.: AQBG/FXa98syEQywC0vt6Oi3UF9glSe+WWCzhwoy6xbKXow3e7z1qAGowtq/SymZwV6j7RUdVC/Fg5WV9CfX6qzc98MFuaqKZY71rh0zzz0FoVOIt31uvuzN5zSSZd2fwH2Wb32+C/T+0ANDzR9egq9Y7M9M9bpDdJGStdhnBE9Lh3IOy0maQ517Q91evvL8L7xBowZ5RSci/9+fdbE/lrGgbplEtD9Q6KpRi3aZcWP2WT3PD+hxa9mgfPtxK2Eu/R4Z8o/086FoUdqH4ZZRpxvnAaaNJiG4toMsS5PAqNFT2S8QQ/EDki0bDJ1pywK4EnjE/ngjQolHKNKmqCZdI9RmDhOx5R+o3IBVqYt4Z7wKDIPuoj/OyNPS/YB090IAOgf71WWWqGNZf8XmYfmksZernR1pb4WX9jQ=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-168786706
      namespace: default

