apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rt1
  project: defaultproject
spec:
  agents:
  - name: agent-doc-tb
  contexts:
  - name: cc
  provider: custom
  providerOptions:
    custom:
      tasks:
      - agents:
        - name: agent-doc-tb
        name: wfh3
        onFailure: unspecified
        skipConfig: {}
        type: workflowHandler
        workflowHandler:
          name: wfh3
  version: v1
  versionState: draft
