apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-134840445
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQA84gTEl9kl96SyvwMHFx5oH6u3LCLKj/iiP0JC5AahFnSII+ycj9cmEBAqEyngSsiXSOZZVEuRt/JYqzUjCrBc6h2vKHrDtqbYLApiPgU3/l6eyyGasgxjtshsYSVzpTP5UrsaJTKVHtwH3MOQJniIqpVMwOTNCUphlIxUYx+taj4vyJxPe3TerPdcyENDAnHjO9Fe/tX9phLETM9vHvkQjL9Ra9K9ynd7fWf4ogc5PlWzmbLsx0NFf1Q1bGh9RS/WdS/SDH/nl/y/mywBVWvw+9l6SfoTqo9SPl1VggNr4EB69JHElC3+IT8UIul37NZb3d6GrE4Pda9bNb878Mx5AdqXNrryD2Qihou1aReQauSKikRSVzbpdbf1t4tu7sctMt6m
    AWS_SECRET_ACCESS_KEY.: AQA1IVVO4lgM0lulThMBE2QD98G7+I4B42kg/QeSYuJPIM4noX6fhRvPza23aveU8wgip6vQaD5XQITznjEpf13RYFQtaU49jR37X8IrA9EiVjPY7BY7rsEXifGDK/LIg7UGisQ0co/azKizbN1Vi6JQjYaFfephTh3TjCeIBJB0IeY0MZ5eZ8eLRaeTw4Qb1T9N1c37IxGEav1BLB+lKYGFhWdmjMrn6cjnVKMkGz7yQiDufsqhVFm74l1+OZeFf4JNuDDnbAcN+JS518QQWW+Tskzh/YIapmLJL9NjYELdTgeqFybZI2XC8KccDYzREiC9D86mi7l5CakmIyqbpclfaLEUKYYSSHPzrwCVSEqi4FzHgc6Kr5IC00L3x7Rcl1gzJHfsqeIZ7j4+Zj65A1jlq3AQXVe3Gts=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-134840445
      namespace: default

