apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-779431138
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQAX77vqSqxEW+mtkDwfdDrtE056yvaUs+LjhrpO/XlEEDz/whytBdxRBcHzoxOwP6LumkYnztKG+Xaiwz3QRgqhUJN7RWPn1+GOPrQLXs/LgRw0omwdWSmJO1mNzl/5hbCXMhlqkBgbopj3UycB3FZJIhtuHpMHFUDCap6k1fO3qBleVJ+anD3Kq/ygJcTiyhgHr53cH4oKTYXsALFTSfTKU1AbUheZtSLjQS1+p8+MWGkYnmvYyFpCyXLSSIJ9iheKDHvsVAbFt0R1fpVo0UYVCEvXoUMQfkZicfn6AunW0ldf98U799oV6F+p22ZHEPRE9GBJZJJsUDbxJDMc6QDIXgOWNTVW8+nlNoGEHwwEoiWthKobgFWLrJ23BmziMfU8XQbC
    AWS_SECRET_ACCESS_KEY.: AQB2GvUDeKRi8cZL5pmtnocjlnvJBXVf/u7G8wIpnra+BVvq22ixL5JJosRrqr01WYwyVyF3vYeOUtNw8Edht2aCFWqLv0z//QlSXgJTtvB1A5FJGteL3z7sR68SpOLnpNlOEExwk3+SjY0n8NRiFpUCCFnKG1CmveUvEJrZqH9gViP+0CxmePZEs61OKmhzzXBDFYh4YZ0yoRTNaz4zHeQ9OzhADA2M2T2MWJAwK+pI1C74vwQRoln4iVRG6BR6DCODwKo5Jdi4MnFEpA0FEcDC5Fyj+2Qg8MKf3ZS1WCGLPtc5iLkvw3xYMOH822TeDJxTxCQfJfs5GhujpUCNTVVxFVfqMpWB3ub1ol3iHQqy5gZU5Lxi0dKn7VBsXsd+oQ+sIdqZc6/iR75WbUHkE9UvCv8I2LMsSvA=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-779431138
      namespace: default

