apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-git-p
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBh287JF4EfflGwNa1bBwt3m7iJ3jfox+DdVxK8FwkmiqSqZXPZFEaaJYX6LstL6gS+EgYWmLb4F6nnJcW6T1UNRJbqYMAbdJlYbTxkYUkK2UwMM2ldOwBvsTjxi7CUrYh5ddZBL6uCo47+6+bjaMKsnSHDF3hYdWUAfRyo3/4zqhe+s6MINfB/tXJn/NeOE9Gr7cn99uOJkdMvzBKAaMemU1oJ8DjU+QiE+q8FuyCRqBl5uy5qHgYoW7LK2Vviwa7mY9dp+oE86r+Zfh8ekW85F2W2AgdtJhSzyutdXeV93UXtIEDd8lmiFVBHZCTcH5ut3BwcYhkUN6/tKUAtWGzAOnqVayL+IxNS4tDTgSYQUoEvtXxPw2vCNp4DYHqyumDcfnnnO1CsTawZALftamImhYMjN9rdcjo=
  template:
    metadata:
      creationTimestamp: null
      name: akshay-git-p
      namespace: default

