apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-18750073
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQB4JVjsz8wqjfOoZINcbGpblNCcD7SOkx3siHaXTk4KHNBubv9T+9qvF+kl/DnEH0jdDvJVy+56YJ8IhEw1T/g+fNQsMdLJme94yE0x6GQHOA6fgw8Ly6W3O8EHGkb72+kds7kFJ8BSMPCz595rxNnIrEi1wFero6pOTjDxLU6md5pGutaTndgCNRrG5+uIHqLzEqLauBj0t6MGptvjIBaaIY6UwK3fY0szOCbKAobPDH6WpzUWY7YzC8u1VeEQiv4G2BvYyTuz6h5FaSenfObmo93d9uEJcYeSGl5ZeIGb5nzd1Z8dlcxhiu5bfa297Sg66WO7+RWsZmm5tVoiFHBTm8OYABM7RwgEp6sqQiVZbRqxYeYJdHPEXKU/0F6BLlYFz7y9
    AWS_SECRET_ACCESS_KEY.: AQBxQrOEpRdkQEC+Xj7yZwI5H1nFEMCAk50nJds+SWbCKOeA+Q/590KQv8aV4NcCqW5wda1wMRlyHANPkL9wkfQ49hrTNCZWcb608wj1wk3nAVlSYyxnNF6nRW6GLbHk97+FIXRy8UUgbsO8DNSfNGlvw+IM5HvtOlf1LqEKvlS66zX27R7oaDW9nFZJh3EfEZ5abdpb6J6yQ2WWh3Nl3EZb/PQlabGpFwFKCLOCeeJwiWLXN+M20egtxoly6ZSTxcoW17DA9sD5Gjfo1de7xgQ5y7qwdAsQpIdno48hlmQFH2OQFxv2OOVN0nDG2i5nBrIdOUX4Glcx1vOhPUm8YonB2+nED8L0QMr4BTK3bSZt+sPWBB3jiPNARr3M9mS5ht1nnDLyvYN+z8LFyUr4CkO7STknWN0KQYE=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-18750073
      namespace: default

