apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-ec2-config-config-context-541257
  namespace: default
spec:
  encryptedData:
    files.0: AQBm8rLWvd8U1kobAVeKd7WR/q7ElG+a7CdL4ctPhpbpvWtWQ0FU072+VxQg/wcLGyZEBRs9km/Lx1GMdtjJi4Cedbtxfon6K3In9fdjtQjBqfo712oTckuSvLCRLIHEJFreV6kpuRp4/Y6frBXPXCC+CLHZTWnyG6z0fg/U7085TJPb1TFYKjZqEkOS1iOZp3ZOFny1dA6LdAOcEL3ZA1Xgd7XHa86GB6AbXaIV5FvZ/RbVBcBiB3RV+hH4UIviEVmPHWXth3mgJ+pC/HBpXdHNDk8IrEvqKOwelW4tJZGzL0DRE5ZO0vYgaS8NSRjGDxldf+nK3/j1dmcJo3+ux3oQP0xGmbOpikE2MDUzmA7FyMM3CSQzvvleVIcS2L+gfiI1Cc5oYwGwhnZvV60kKO/y3K303mwuMUpjMvqeaFuOZxO/jyZmpQ2iukLeFUQIiyd98c1Z5BoNS9rnwc8VJmCFyrUA
  template:
    metadata:
      creationTimestamp: null
      name: rauto-ec2-config-config-context-541257
      namespace: default

