apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-repo-559033448
  namespace: default
spec:
  encryptedData:
    credentials.password: AQARlKPvXRjtzjWB2lWhfJ8xjGRtNo+PDWQKgQqSGr8E0V7UpQMz9dRUub+lLhLS5QcyFNQtsLKyKnX3409yLyJNZ7JVQ1WXAJ+5VF3C2EVNKz5auf+IPecoFCVC9XbmsgQdrOmKk6aQsfZZ49Vd1VzC5Xi0aTyiNlRVskLmXpjKkM3kwqznTwhO9N4aR6MQyGc7CPtf5b5qdlXbmq9CBEz/1UPNZtduGFgs9Yk2aFi3mK4OdKCiFRSd6HwiprdZpPTIQdKVmqs7uw3ffPzR75HKMWX6zYROC4PIKdPRge+W+k3uP/C9bGhqdHHyYFJDS0bq538DjduDuOr0UmBfmCWfaWWajQalA8H9mRa43DY0d1PosQtdq+KtvjskRhQ/
  template:
    metadata:
      creationTimestamp: null
      name: auto-repo-559033448
      namespace: default

