apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-772801969
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQBvw7u96jQXCA5wpuEH9bV2SZPFhPYibuyVyra8xRi3VJS7DkTrKvWsyJf71sOjre1kyU8J/FPHM1yCHR6a2bYCkSxt1b7DWOSBbaogNjqeYkK4w8fXSVYZnDzm4UqWJFLY+Rgk1OcTUE2J5Ouv+7XcFKwMiiup9NTTOJAG3AjoyN95eh7paZEkz3N85AoLsWDJ0RdfM0IJJzXwj3TewarsvFtp+WWPldljxVfwj5jr1kRb3AAR05gcqihTy4wns3xP6RpuUug6RZSb5CR9aowMS89X27JAXNHiQeiRrd0KbaXx2qXSAJ3vIIdnRfL/mzNTVPoWBFX8cqWlynsK6WsQqeIMB4xdoagA3UtF/t3Bf5fDU20G1ps/lPWAMiXPe1T3KSPY
    AWS_SECRET_ACCESS_KEY.: AQATOy6Ry+LUOrXZuxwZKrCA3iLbI7qydLB2dHGv+QZRGKXewDaip0Rpdj1rjCNAERtTeyI0B1C7qXtd3PErL6dSh9Fwk+CZRyDqNMUZ/zmBEheVQgmqVCNScdY5nPMl5QB+IA4eBTWdBkBe2HEKb7DTHWfPebMNz+BkhBo0cV3uhn5dzFTy+X0t8UdEWCaITJVPniX36pqEf3AKaW9PgON1RQyAganXxBk/qo3DlE6Oi8JDWJlLmojG5V+UdkxZE6qPQliwF9ftbtLvJjA7MHq4dXPdDhsOBMKvDrtXFR/HhjulEfLJCgT97LxjmqwPRBQDwgwO4NHyAohGewbEyxQoPu8cxbOGYMhvkjM+tMlnmZ5sB2oG4sWECf6P61iEfxwxVIF6sA9pjd4YZDpRGDw3orC0HTNLGXM=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-772801969
      namespace: default

