apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-config-email
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQASmOLVJr3JZ111D6GHXeXdcjv7akDQrKhPTRgPKKtqSq+aP4vkQ5Kckbu7VVCL3tacmYkURfwfihNLafSxJgN4CRLbDQTMxi7s7ymP6ZArrOUjA964dsHakuQOmDxwBPxPRBRElTBP3Vp9Mh0tvlwnM5R2ACFATm7Wjfw8/pOBWn1MV7TTUX0ZdHZdLqpXLMqv/dal586CcXHtksM8XQ2vRlou9MmQP9Y5Kb/tuB1axbAVAoODYjwytUKnrR2ZScaeWYT6tZWytWlgBt18mcKLx6iCAFrlS89HjRWEMgxciq+38lJArKRaDOJ/KlV9nvKvXuEaTRr1qGSORYp6jPnx5t/Uw7Qvh0bt07CanSTu/c/LJADfx7E7hBjbGbIfq/TGb23U
    AWS_SECRET_ACCESS_KEY.: AQBh+fMy5JkmVUq7A4lxX+vKe9c724dgAQqE4Phpn5QwrY7+gSvimQRbgJnTIX4JK/QRaDkQoDWvaFhzuYOLz/Rt/NnmmOsplOXGhq58EtAnh71dAy+LWFY7RYLOcMZSqvSudE4n976KfJRCIbeqN42YWsXwcciJM4qBwEawlC6H2bWidnwzLTBPV44ypN7BshVqjCQkhv1fy1zuXhIHe21FEkUHE3mWkkd2UTYBaLPatqYQIkQbZu4g1dgZolzRrI+VSQckWxvYjLByV3678NEyn0QMI92ypk15qDcvrbcufHHLeqQoKq1BZ3bvBaTgVbrKHlUpd4ksmK1EEUf05XgDptOjNK21+pF/bqpv3W6opkj25OIgLjXuhMwJp09WYOX9XJ32iHsOXThVGP7Dn8M84Kd295yJISQ=
  template:
    metadata:
      creationTimestamp: null
      name: aws-config-email
      namespace: default

