apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-repo-verify
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB5Eq25xNYb0OadZwvnjDWi/J4vxIJrZDPixasUn7xgSLqMWc8W9CpKwUzumc4/8BO97yBXs6Q46AaXUoKtyec1cV/Ni+21cx4ID0EID9WBHjZXP1Cpo7W6QRApSVFoJUJSD9b6RjWjqLqo45GdfDzuAq6Ew+JlRdQhtvjYjMVKBKhpLN1qeLRfhih/8WusGw+UtjyTBY9iYkgZw0enk7zoeWrQrmZMkgc1ftYKFAzzJe9Xoj4EGxFbGBIlufsjWEGvt//kAhA/MXwvkFYQ9M4JUUufi7Nx3AEeSndB/A2zNuNFwEpL0i76NdQlSZY1NQuOZgekNysScpbjqV6r36SZxkuaDriROUh4qqwpZ1g3gp57i1WAM7KrIWzpzHu6mIUx8oozhYQ544BcfODfUjn/hZx8odP+GTdeI3ahEaQz03rqQSUS94fVoiWgkVztBBw2ieUP7MxQjAKWXOW/Sh9Xv3kQmqRw101D6WPSDQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-repo-verify
      namespace: default

