apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBFeFrhbRdjLxxbVDLIIoVv6Vg+RQcH4TUkb+eudjDMDUzDcg47Opa5fQ6yTlrZhUy7O4hdjod8bgc+aiQwuL69JwkPMezMmHeiexVf0nEz7lpFmHJTktM4UtZm3RXpgXFg/7la1ZElOn+iIU4U4R1B+88KQX3IqM1t4E3QtG8gVgxE51R1lTWTkhGApkP4o/M5riF9YugnxmAw20FqjO7Ugk2RW+qte2pniRTUYp0IVfSdhBTdmce+Do7rO8sKs5Roos9gGTHHb6fCPasl+lehACsdatgskXjq+S0FdTxmpj06prKSrBkHBwHBZyxmISxMAhUcrfoy2NmuFB4Ldc3zouuhpP5yv3SWsf1A2+3E58vWUnQWu7SDZJWy04gW2oW3gZCGApqVMSZebJo5Uj1RcUJE+vLE77tdyISNs4EaQGDsBwgIy06fplmE6tJjrQbcFGaHFgUi3QSvGqXl3qWFMoNCIBwa187055FxJQ==
  template:
    metadata:
      creationTimestamp: null
      name: akshay-repo
      namespace: default

