apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-repo-989795850
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBInigtLDxY6ul0dRL8yd+NcWx6K+cHHoS7VJv0bu6vpYLGF8abWKK8I8zxYWAdhxELa23geYFdXD0AXgze9ByN8xX5PClbPYtVo8IG/nuQ+zxOwX48MhfVeP3coogVCyrYZbwOSvcBuK+6F8qVioz/Yh/8YHFIRKsZc/eQ2ItPnw4ASZT34fKBdYBUPfMeIW8PvV58Rnv+SqatEyJgE+3brA0hrmOc3dM5D/3O7PHqH/K/3/66FUEzCqfuwhNJz4CuOAUb+N6OtjWHCH3xMcSzoRrCgqiW1P7yuflXyezp7NtZAEkJX/0YW4a1sAYfNUwr2MFdhL9NWhrVi1/6FK43HRoO9S/x7Ap7E2xcLneIa4Jrj0HnVeRTinwOAI/T
  template:
    metadata:
      creationTimestamp: null
      name: auto-repo-989795850
      namespace: default

