apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-333093251
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQAJte6bqrT1IxWI2xm7OpJCVHkpwBXFO0mOzNvkX68FZEiUf6slCdqQaTEtwpfoItkd4efwn44GS2tGkjv5jJvQmRIBa3jFolP4bL6AuFJNRKqYfHmXRzU+A7DiS8+6jHMkJZPvIjcTJpsD6m+aG144uEIRNcKyHziI2lSI3yMpsmnxSpTgQZEbEEZsqhzKOiZKRxOPA7dDY271YKiPhWamiD9QuteW11o0YCzu2Hqighpp/tGXg09l7n3PwcNM2VK3s8ZNqiw/rayQFfL8Nc0ZjMm50kg6KPdKYt9qB2xXZq/fJ8TMfxAbO4aalZDmy0im9PQluQ3V3eBOtgskFqlkSCcuX+bsMi3lggoMW44+gu01niNQcLU3TkbGysNqNZLRPnrF
    AWS_SECRET_ACCESS_KEY.: AQA77TcKmP3jpRCou5CsoznRh1H09SYDLMUn5EXgbLLSU8/s+r0VG+dy+tzzP9h95PfH+pI4DPzxnZ4BQW6/Lhw8nJGIO+18f/fH3RUXnLX7bta1L6nqG7etr01lXMDmFphTJGCiV1u0G4oDk6yp94D7HnRAQrcIgbV54gnDFn6fpciDD+tczmqqJyLg3Xx6OqksPwKFdyPeuY69O9DegnxEEMBx5L3xma+N0DlqMjirUOhx/OiD7FeDIlYEPsoLblGjrcXeTG+WulwwZKyMDgd49BKJeTdBpVwynpYT6hOSQhNVOapwv663I6riz0aSpGjyZMdekJllLc18WXR5r9iqf2mIzzU4ZPnDvBop5a9AeD/ap6bE0Q+0QNLAR+k8RPQHyp5JKE7DcI+XOpfZkGWhPrynqLKmyqY=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-333093251
      namespace: default

