apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-259402922
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQBFWdhuzkKF7ilUliwdspzVi1PxMqXC1CkanTWdLe33Fxm3L6xw9SRkp3W+h31z+wDCVWDRVVz5mgZnBxuc+cCwtprjHn/VSkHnvsp2lZx5ep56cZnmM5ArGmhq5FEUEi3DlqbydxahgLS6CJPbjLIM9s2yrbuPTdVb7S9H83gHdyw/zaBKQXNe8Xp0DwffZpD/b1Qbazon+gQiWNIox/Nw1bYDt1fxTYQztTvvJAZTOBiqmt78Rf2km4+0T4rCh/f4ftoLkI/drRtJmGAZpw/IvKLQ42z3iZnxlT82G7sUlYL2Gv7FgBU1VY/5JhpAfS4d96nfvE5r5ZSMp5d2E6pOfYwDPxH+BUSJrIUduKdY7mv1oNnWEzImePKjD997aRpezlRW
    AWS_SECRET_ACCESS_KEY.: AQAt8Tes5ntj6/3rHJIx9zFwLkFvmXwX8bB5GT3tCvinN/tR7tJS2pZbwycmOm+utNyyXN8Tob+u46WLOgA3diQJfaM4I0Isc2CqkHljjD+xXr80sPxEVR0YtONEAOw6MPiUAcG6ysrwxHlOzxbgbmLWM2Hsc45zZE6Ioa3Ty3vrk7ECQLbDbOK747hN/v6EchoLgBLQdarR+E9bRG8oPQ2cRnV97MtS5fjA1HoFDpRq62fra9uHtgtBtSOmhUUHxTVf/M107HQVd+xLO7CFyvLGYHxqsGjs9vlGxulMswIfTQF6YZdh0jp835CsAcvvs+7Wb+plutl2rGTxN25gBtr+sLmevu+E+VXNF1qTZyJkv0LSZwLnms/Bsqu3I/uScpEqTVOAD+2OHHRiGbzJ9DPUFlJyfslYWfs=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-259402922
      namespace: default

