apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-136687945
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQAHBVhwDu4gBPtoZOI5P0bMUB9x+qmmx5WTwLAonVclyCy2E6zOFnu0Sxg1pLvIMN3NGLcnWwtZxJZbHbDFrWcuHOSW+RPROu8nQaoF6eJQLPDS9yvoMWqSu5zvErmULaVc+r+sm5pTiCr5wz0ktIGt54mZdyz52c1hu1GOhijF90/yzrXOkttJ9BubpsADrmkWvSTAZNLiYTb6HlP4nZDWuiDOKZAF0XUksAm/r8hi3t0KbIP35vo8yreT4Gckp75JaWldcIvMAGm8Ps44TQmAqRAK4Ql/8QWinUKp7RdfsyXb8aiyX1cCD4d/uFZOSxya0yucaFtNYZizv51ZDG8FbF9VpT2G75WEbCPxfekdrau7iirWuDAkds2z1EdqOc3S4upC
    AWS_SECRET_ACCESS_KEY.: AQApBv6BgxybF5jMMvRNKOiZ8mY5VzFH2LhTPQPjSiyF5VzwI4+DHiXcNWB7wFqnmfcIyR5LPBk7BkI049tcX5QI4Pwnqu+qm1plgwSNgUDmoyZfna43uEEreNikbzi4ym1+0puHXTDMmiQLW26mcvnmGa0lnKhuZGc4xip1x78ZlmpnMrAgfcV1qrIOxtfXBsVr3IQqvV6ReYrTpHgHvzhA1VFHC1jYAgxJya3RHosSOTn+9FS/TSwej9C3mE60TnM2OmzybJXYSdAPx9P0C2VeJG267wYY+pyFZ+BPKdzWHShE7JD1fiJEd2cQuGq+ZFIoZT6ub20HHkXH1nlLLJ+4k+99Cwh771kphL1c7LPwQWwNnbf4o0RUcPX7Gy7brYl4BDUVdxjZRyqRKC+/1NW+S30c00ao1Iw=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-136687945
      namespace: default

