apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-143097535
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQA2XQ/U1x+BDfmtPhnKpcqVHg9xx5OiAc398ydwKqUJx+gyPtAVhS7lQWY5HvEtfq8Pv8hg1PYY1kF5z3JsI0ErUChRWVQUnyUl5GFUMo3oztsBUaTUrkVZaRwHTmtHFtj2SSWlxsTRLvG8bXjR61UDAyXGceMrUPuzA2S8+2iISF30ud9KqJ/f31/Mhncu/NNyh5cXLkJywsjrdvm4hfVwD27CDnRjuYWHKvUMaTQEcgaWUYwDJU4mr8RVI0FF7LhQcyfI7zZSK+R8M81bYsejWMY8Pob7mb6hrUWe4KTK5oiSnaOethCrb79FMOR+oLTblABUQD1bREyVaZzD04GwNkkmqHWXQ5IKSC0KV35EXch8MdsPsidZeoS+Dd3zWhiQ+/EB
    AWS_SECRET_ACCESS_KEY.: AQCNfW19x78zseolJxnH2pQyHV5by8jGCxNvURGklIIB8ybo208EK7xd3slOR9huiHx8WUQ/r/IM8REs7+eOdO1i8tTxi7e62j0cabbK9XiZ/mBuBnomkFq3Anuy6XXxn4/EOdy7ZqDB+2GC/VmlOf2bLsj03RpngmBmQaHrPUdU+6pZ4RhyffqLJV88yTM9SHbglyA+njdX6jQ+Vm85md9hpJHdZHh8nP+1VUC4LNqG8NnGdIld/MgqAjWNzztF4tYIJx8KryNqpHkdZd0IkpJ5OqWKHkBfMVpKF68ZirFiNAAaMrlzZ2lFOfz+mt6TLI4ikD60yZyAttDmJWuxqPa33+JIk26DCGYBRPUwenIZ4hHS/Xk1mBUtHF7AACVVFMXuQXjH0TTLOvb8te5ktlZ08eWUM45P+Xc=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-143097535
      namespace: default

