apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-helm-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCNQm7HVGB9gycgs//LiXfUo2K1NFIrMLz9+rcY3cYIvH20Svtbw7sELHSIdtxHxhz3Vt9rEUwp6rx6P7P8teY3273xQI2K8ft5Ivgl0zmCIITYIRowLNwRUe017BW8jYqP0qrXz7+aeQU2HQyzAUipkUVZ/DylQ0EQXhcJNpdIWGh3EIXa1xWlvIDyUuT8YwKPoSOcaB7h/i1uwp+rbkIDYS7PB62zhxd++LUBpoHWWQaAGxc6ehPv8rWdsp49mZ/F3kVQFjw+A++RCQbfFscG+XVshl/FuVBtvu1vHHRRGJfAUXDyoIz8jaIWWOIDGgwCqZq1ltDHSpvfLswALIl7rzcoD2Z3OOjc48tUHBL0iaUcWcohZo7btl4=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-helm-repo
      namespace: default

