apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auto-configcontext-224314498
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQA5eb1C3IlzOYXywxY7eRGZH5jdyUMnPUqaT4QoLjO/7esaIPEJ2/C6vUHkZjgArky9HXZalPpr0rW6HrBcEwqTvv5PXOxDbkKizOWxtz/RMHzDuWaQtPUgEb4sCqna/DhE/ZKAlpl2Dq31HK3620N6RKO+uZZF104g7P6ETFi1w3McgYHi8sdcilVIrvdQfY5pq2D5givZRMwqRttDJAQZebd4YJkApljIz8fhVpKjprzBMZfY+fmeQpa0PWWnZm61jcDh8Tj+9HyrvcfRCMp3m1Mr9KssOtLhQDg1I9YhnrEqidpQHVNHTzhsEimq7HxCWMoZ1yTTss8iH0k/oc8YNX+3j+KllyUI7G3YZAiQsXzZRo10yzw/pwmHKBm+Qit3ImcE
    AWS_SECRET_ACCESS_KEY.: AQCDiVdEPXMdyjPeHUqzK3tBrdqNcjIbK+WtN3mqPoAXt5J/Lq4KiNbkTLXtwXAe0g9FR4YvIGPg923RQsuSEIWcKD/0Sz0U8NI1TMbVE6D/VH7m/abURp0E603idcgBNkZfWRyli527Xt+2+t8ZLL341S4PC5lBWWXewNRTaQnkBsyn+kJ3U94T8lxIctNCWQ5h27Io7u7YEBpmOdsgwS77YraV1OUHbMXfjt3HMajuF6dYo7PfxPT75gKKyimd/Jx1Y9v1r+Gzep5wVsWOurSJqro6CzxXjMkTbIlV+2LkQy47ZOE9lwkje1WTWk55SIY+nVQ/bv6PmBti5P9EuejTD5QXfUfr9Z9RnhZGq9mX8VODddI651+mIDeWHCGC8vB9pc9TZTqJZHr1Vfdj8kcRFLaKoa10Nh0=
  template:
    metadata:
      creationTimestamp: null
      name: auto-configcontext-224314498
      namespace: default

