apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-git-p
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCg8ED0oT6CDEOOpPJNpqWAbD/VewB/flz6zmcebanUU8B9kMva7zU77JLEe2nFutRf0g0yOGohAOX+yTEFynKlhNB5QbrV7xDTSwkoqzUtEudlVLrsAhEaqSBvjCzQ+G/ZlPNbcIHaWkCupy2a9Z2nSjAkXL7eEOUTXKNyqNOe4tyvjuidhtojtFZxCFwF4Bdhvr80ZawSYMChKD768FWRHXwSvNCnaYQbdJv5+jyZP2kNV0HmEvESSJMpPJtRoEy3lW1FxkgWViFk0RASOjqQSDmj4/YGTYYreaTaKIvUH4cwubHSoLI+lkv5QBUoMB7Tg0pP1WzFdc8JTtLM23pEdZJtX8bn0yEONcAyxpybFcDqDa2fnPt3b2rdRf5OTsYAVeGkdzP6rOFcd6doLy4y0eNIneviMbc=
  template:
    metadata:
      creationTimestamp: null
      name: akshay-git-p
      namespace: default

