apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: agentk
  project: defaultproject
spec:
  active: true
  cluster:
    name: c1-tb2
  config:
    concurrency: 55
    environment:
      numWorkers: 15
    kubernetes:
      limits:
        cpu: 255m
        memory: 1Gi
  type: Cluster
  version: r4.1.0
