apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: agent-4
  project: defaultproject
spec:
  active: true
  cluster:
    name: akshay-amd-tb
  config:
    concurrency: -56
    environment:
      numWorkers: -56
  type: Cluster
  version: r4.1.0
