apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: agent3
  project: defaultproject
spec:
  active: true
  cluster:
    name: akshay-amd-tb
  config:
    concurrency: 54
    environment:
      numWorkers: 14
    kubernetes:
      limits:
        cpu: "254"
        memory: 1Gi
  type: Cluster
  version: r4.1.0
