apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: tf-k8s-agent-version-demo
  project: defaultproject
spec:
  cluster:
    name: akshay-amd-tb
  config:
    concurrency: 55
    environment:
      numWorkers: 15
    kubernetes:
      limits:
        cpu: 255m
        memory: 1Gi
  type: Cluster
  version: r4.1.0
