apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: agent-prod
  project: akshay-2
spec:
  active: true
  cluster:
    name: akshay-amd-prod-2
  config:
    concurrency: 55
    environment:
      numWorkers: 15
    kubernetes:
      limits:
        cpu: 255m
  type: Cluster
  version: r4.1.0
